root: true

extends:
  - airbnb
  - prettier

env:
  browser: true
  node: true

rules:
  indent: [2, "tab"]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/jsx-indent: [2, "tab"]
  react/jsx-indent-props: [2, "tab"]
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "rollup.config.js"
        - ".storybook/**/*.js"
        - "stories/**/*.js"
